services:
  postgres:
    image: postgres:16
    container_name: secureauth-db
    environment:
      POSTGRES_DB: secureauth
      POSTGRES_USER: secureauth
      POSTGRES_PASSWORD: secureauth
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secureauth"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: